version: '3'
services:

  reverse_proxy: 
    image: nginx:latest
    container_name: reverse_proxy
    volumes:
      - ./reverse_proxy/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443
      
  backend:
    build: ./backend/
    command: python manage.py runserver 0.0.0.0:8000
    user: alice
    volumes:
      - ./backend:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      